<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_cc</name>
   <tag></tag>
   <elementGuidId>96bb40b6-153a-4ce0-a251-557355b70ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.with-promo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.with-promo</value>
   </webElementProperties>
</WebElementEntity>
