<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_continue</name>
   <tag></tag>
   <elementGuidId>1def78d7-6bd9-433d-889b-3f02c1d91091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.button-main-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.button-main-content</value>
   </webElementProperties>
</WebElementEntity>
