<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_cvv</name>
   <tag></tag>
   <elementGuidId>9e6d0b60-236e-462d-8080-00c4e9fdc142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[placeholder='123']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[placeholder='123']</value>
   </webElementProperties>
</WebElementEntity>
